### ISSUE TITLE
Creates superfluous + at the end of a Roman numeral analysis

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/plains-cree-fsts#1]
*From eddieantonio/fst-lookup#5*:

> This also appears to be an issue with the FST — at least the one built in [UAlbertaALTLab/plains-cree-fst](https://github.com/UAlbertaALTLab/plains-cree-fsts)
> 
> ```
> $ hfst-lookup crk-descriptive-analyzer.hfst
> hfst-lookup: warning: It is not possible to perform fast lookups with OpenFST, std arc, tropical semiring format automata.
> Using HFST basic transducer format and performing slow lookups
> > I
> I	I+Num+Rom+	0.000000
> > II
> II	II+Num+Rom+	0.000000
> > III
> III	III+Num+Rom+	0.000000
> > IV
> IV	IV+Num+Rom+	0.000000
> > V
> V	V+Num+Rom+	0.000000
> > VI
> VI	VI+Num+Rom+	0.000000
> > VII
> VII	VII+Num+Rom+	0.000000
> > VIII
> VIII	VIII+Num+Rom+	0.000000
> > IX
> IX	IX+Num+Rom+	0.000000
> > X
> X	X+Num+Rom+	0.000000
> ```

**Comment by aarppe** [comment]
This was a bug in the source LEXC files - there shouldn't be a feature/tag with plusses on both sides, even when anticipating more tags from an inflectional continuation lexicon. It's either XX+ or +XX, but never +X+.

I just fixed this is the GT source LEXC file for numerals.
