### ISSUE TITLE
Use correct spell-relax file

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/plains-cree-fsts#12]
We need the latest spell relax to be compiled in the FSTs here. Problem is, @eddieantonio doesn't know... where the latest file is. Could @aarppe perhaps help?

Related to UAlbertaALTLab/cree-intelligent-dictionary#146

**Comment by aarppe** [comment]
The latest spellrelax file and how it is compiled (from crk.hfscript) should be the following:

hfst-regexp2fst -S -i $GTLANG_crk/src/orthography/spellrelax.regex | hfst-invert -o crk-orth.hfst

As far as I can remember, I've tried to have only one spellrelax file for all purposes.

For the record, for the spell-checker, I've also tried to specify exactly the same modifications for the error model, though that requires using the different formalism in the *.default.txt files.

**Comment by eddieantonio** [comment]
It needs to be INVERTED?

**Comment by aarppe** [comment]
Depends with what script you compose the descriptive and normative FSTs.

If you compose it with the normative analyzer as done in the crk.hfscript recipe in crk/inc (as you plonk it to the input side of the normative analyzer, and that requires inverting, I believe):

```sh
echo 'Composing spelling relaxation transducer with normative analyser transducer to create descriptive analyser.'

hfst-compose -F -1 crk-orth.hfst -2 crk-anl-norm.hfst | hfst-minimize - -o crk-anl-desc.hfst
```

If you create it using the standard Giella Make file, I believe that knows how to properly compile (and invert when necessary).

The one annoying difference between HFST vs. XFST and FOMA is in how they interpret input/surface/lower and output/underlying/upper sides in some compositions (which I've never fully understood - to me,  lookup means looking up, so the input would be the lower side and the analysis the upper side, which is at the same time the underlying form, which gets confusing). From folks in the know, the HFST solution would be more proper, but that's less of a consolation when XFST and FOMA operate differently.

**Comment by eddieantonio** [comment]
These are the results I get when the spell relax is INVERTED:

```sh
echo "acuhkos" | flookup crk-descriptive-analyzer.fomabin
```

```
acuhkos	acâhkos+N+A+Sg
acuhkos	ahcahk+N+A+Der/Dim+N+A+Sg
acuhkos	atâhk+N+A+Der/Dim+N+A+Sg
```

```sh
echo "neeya" | flookup crk-descriptive-analyzer.fomabin
```

```
neeya	niya+Pron+Pers+1Sg
neeya	niyâ+Ipc
```

```sh
echo "neeyu" | flookup crk-descriptive-analyzer.fomabin
```

```
neeyu	niyâ+Ipc
neeyu	niya+Pron+Pers+1Sg
```

Does this look right?

**Comment by aarppe** [comment]
Yup. I'm relying on the standard descriptive HFST  in giella (our own script doesn't incorporate the regex's concerning various permutations of capitalization, but that shouldn't matter here):

hfst-optimized-lookup -q src/analyser-gt-desc.hfstol

You should also get the same results with `ucukos` and `ucuhkos`.

**Comment by aarppe** [comment]
We will probably want to implement a spell-relax rule also for word-final `-uh`, so that one can recognize `neeyuh` for `nîya`, and maybe some other interference from English.

**Comment by eddieantonio** [comment]
I inverted the FST as of 751f86fb404bb21d6d5be886532370521583fa8f and now it works! Closing.
