### ISSUE TITLE
Inflection identifiers list

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/plains-cree-fsts#2]
Would be great to have a JSON lookup (or similar) of identifiers for the various inflections, eg:

```
{
 "PV/e+{{ lemma }}+V+AI+Cnj+Prs+1Sg": {
    "mode": "Conjunct",
    "type": "VAI",
    "variation": "VAI1"
    "tempus": "Present",
    "actor":  "1Sg"
    "etc": "..."
  }
}
```

Some discussion may be required to make sure that all inflections are identifiable using a format such as this. The goal would be to render list of inflected forms (similar to the "linguistic" or "nêhiyawêwin" tab on itwêwina). 

I've [made a couple attempts at this](https://gist.github.com/aaronfay/142d5194aa54f2eb09d92c150c179389#file-forms-ts) but struggle to encompass ideas like "future intentional" or "infinitive (ta-)", or something like "should (ta-kî-)", but at the least a full list of the inflection identifiers would be great so they can be [mapped to templates for inflection](https://gist.github.com/aaronfay/142d5194aa54f2eb09d92c150c179389#file-paradigms-ts) Note that some of these deviate from the identifiers you are using, I was taking creative liberties, however it would be great to have a 1-1 agreement on how to identify forms moving forward.

Bonus points if we can include obscure forms like "weak reduplication" such as 

```
wayâpamêw
``` 

@eddieantonio looking for your thoughts on this one.

**Comment by aaronfay** [comment]
As a note, I would have hoped [this API](http://sapir.artsrn.ualberta.ca/cree-dictionary/_displayWord/w%C3%A2pam%C3%AAw) had a list of the inflection identifiers, however the `inflections` list is empty.

**Comment by aaronfay** [comment]
Also, if we had "just a list" of all the possible inflections for each verb/noun type [like in this comment](https://github.com/UAlbertaALTLab/plains-cree-fsts/issues/3#issuecomment-512654524) that would be an awesome place to start with this.

**Comment by aarppe** [comment]
You can find these in the following directory path within the giella infrastructure subtree for Plains Cree:

ls ~/giella/langs/crk/inc/paradigms/*.paradigm
noun-na.paradigm
verb-ai.paradigm
noun-nad.paradigm
verb-ii.paradigm
noun-ni.paradigm
verb-ta.paradigm
noun-nid.paradigm
verb-ti.paradigm

These cover the full core set of inflections, without reduplication and lexical preverbs, unless these have been lexicalized (in the lemmas).

While I don't know how to incorporate the same GNU AGPL v.3 license into these files (without messing their functionality), the same terms as for crk overall apply.

**Comment by aaronfay** [comment]
Thanks @aarppe, that's exactly what I was looking for.
