### ISSUE TITLE
Possible typo for `langs/crk/inc/paradigms/verb-ai-full.layout`

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/plains-cree-fsts#5]
I believe the `FUTURE DEFINITE TENSE` form for `Ind+Fut+Def+12P` should actually be `Ind+Fut+Def+12Pl`, attempting to inflect with the current value results in an error:

```
$ echo nikamow+V+AI+Ind+Fut+Def+12P | hfst-optimized-lookup --silent crk-normative-generator.hfstol
!! Warning: file contains more than one transducer          !!
!! This is currently not handled - using only the first one !!
nikamow+V+AI+Ind+Fut+Def+12P	nikamow+V+AI+Ind+Fut+Def+12P	+?
```

**Comment by atticusha** [comment]
Thanks Aaron. You are correct, it should include `Ind+Fut+Def+12Pl`. We will fix this.

**Comment by eddieantonio** [comment]
Hey @aaronfay! It's fixed in the SVN: https://gtsvn.uit.no/langtech/trunk/langs/crk/inc/paradigms/verb-ai-full.layout

**Comment by aaronfay** [comment]
Thank you
